pub(super) fn template(
    word: &str,
) -> Option<(Option<String>, String, String, String)> {
    let lower = word.to_ascii_lowercase();
    let values = match lower.as_str() {
        "work" => (None, "do work", "I do this work.", "We do this work."),
        "business" => (None, "a family business", "This is a family business.", "That is a new business."),
        "power" => (None, "more power", "I need more power.", "This has power."),
        "water" => (None, "some water", "I need some water.", "You have some water."),
        "money" => (None, "some money", "I need some money.", "You have some money."),
        "development" => (None, "takes time", "Development takes time.", "This development is important."),
        "authority" => (None, "has authority", "He has authority here.", "She has authority there."),
        "society" => (None, "can change", "Society can change.", "This society is different."),
        "art" => (None, "like art", "I like art.", "You like art."),
        "education" => (None, "important education", "Education is important.", "I like education."),
        "air" => (None, "need air", "We need air.", "There is air here."),
        "love" => (None, "important love", "Love is important.", "Love can help."),
        "music" => (None, "like music", "I like music.", "You like music."),
        "experience" => (None, "have experience", "I have experience.", "You have experience."),
        "language" => (None, "this language", "I know this language.", "You know that language."),
        "land" => (None, "see land", "I can see land.", "You can see land."),
        "support" => (None, "need support", "I need support.", "You have support."),
        "space" => (None, "more space", "We need more space.", "There is space here."),
        "oil" => (None, "some oil", "This food has oil.", "That food has oil."),
        "news" => (None, "good news", "This is good news.", "I have good news."),
        "hair" => (None, "long hair", "Her hair is long.", "Her hair is short."),
        "growth" => (None, "takes time", "Growth takes time.", "We can see growth."),
        "behaviour" => (None, "good behaviour", "Her behaviour is good.", "Her behaviour is bad."),
        "science" => (None, "like science", "I like science.", "You like science."),
        "direction" => (None, "the right direction", "This is the right direction.", "That is the other direction."),
        "peace" => (None, "want peace", "We all want peace.", "They want peace."),
        "damage" => (None, "see the damage", "I can see the damage.", "You can see the damage."),
        "sleep" => (None, "more sleep", "I need more sleep.", "You need some sleep."),
        "insurance" => (None, "have insurance", "I have insurance.", "You have insurance."),
        "transport" => (None, "need transport", "We need transport.", "They have transport."),
        "distance" => (None, "a short distance", "The distance is short.", "That distance is long."),
        "danger" => (None, "danger here", "There is danger here.", "I can see the danger."),
        "living" => (None, "living here", "Living here is easy.", "Living there is hard."),
        "existence" => (None, "its existence", "I know of its existence.", "You know of its existence."),
        "learning" => (None, "takes time", "Learning takes time.", "I like learning."),
        "respect" => (None, "respect for her", "I have respect for her.", "You have my respect."),
        "writing" => (None, "like writing", "I like writing.", "You like writing."),
        "hate" => (None, "can hurt people", "Hate can hurt people.", "Hate is not good."),
        "salt" => (None, "needs salt", "This food needs salt.", "That soup has salt."),
        "metal" => (None, "made of metal", "This is made of metal.", "That is made of metal."),
        "reading" => (None, "like reading", "I like reading.", "You like reading."),
        "teaching" => (None, "like teaching", "I like teaching.", "You like teaching."),
        "sugar" => (None, "needs sugar", "This tea needs sugar.", "That drink has sugar."),
        "weather" => (None, "good weather", "The weather is good.", "The weather is changing."),
        "pleasure" => (None, "a pleasure", "It is a pleasure.", "This is a real pleasure."),
        "coal" => (None, "can burn", "Coal can burn.", "This coal can burn."),
        "motion" => (None, "in motion", "It is in motion.", "The motion is slow."),
        "meat" => (None, "eat meat", "I eat meat.", "You eat meat."),
        "milk" => (None, "drink milk", "I drink milk.", "You drink milk."),
        "bread" => (None, "eat bread", "I eat bread.", "You eat bread."),
        "self" => (None, "my true self", "I know my true self.", "You know your true self."),
        "rice" => (None, "eat rice", "I eat rice.", "You eat rice."),
        "fiction" => (None, "like fiction", "I like fiction.", "You like fiction."),
        "disgust" => (None, "feel disgust", "I feel disgust.", "You feel disgust."),
        "digestion" => (None, "helps digestion", "This helps digestion.", "That helps digestion."),
        _ => return None,
    };
    Some((
        values.0.map(str::to_owned),
        values.1.to_owned(),
        values.2.to_owned(),
        values.3.to_owned(),
    ))
}
